export const samplePayload = {
  name: "Nehru Wooten",
  businessName: "Mariam Leach",
  ABN: "11111111111",
  fullAddress: "Unit A31, 4 Ennis Road, KIRRIBILLI NSW 2061",
  website: "https://www.badu.me",
  email: "buwoceroho@mailinator.com",
  phone: "1233211231",
  unit: "Unit A31, 4",
  street: "Ennis Road",
  suburb: "KIRRIBILLI",
  state: "NSW",
  postcode: "2061",
  country: "Australia",
  dataForm: {
    limitOfLiability: 10000000,
    claimInLast5Years: "yes",
    claimInLast5YearsDetails: "1999",
    situationAddress: {
      unit: "Unit A11, 4",
      street: "Ennis Road",
      suburb: "KIRRIBILLI",
      state: "NSW",
      postcode: "2061",
      fullAddress: "Unit A11, 4 Ennis Road, KIRRIBILLI NSW 2061",
      country: "Australia",
    },
    group1Activities: [
      "Office Cleaning (outside business hours, incl. move-outs/spring cleans)",
    ],
    group2Activities: ["Car Washing & Detailing"],
    group3Activities: [
      "Factory Cleaning",
      "High Pressure Washing (external walls, houses, roofs, driveways, patios, fences, mould)",
      "Sports/Leisure Facilities & Gyms",
    ],
    group4Activities: ["Floor Stripping & Resealing"],
    annualTurnover: 124,
    yearsInBusiness: 2019,
    subContractorsUsed: "yes",
    labourHireUsed: "yes",
    lossOfKeysExtension: 10000,
    contractualHoldHarmlessAgreements: "yes",
    extraServicesIncluded: [
      "Cleaning of Gymnasiums During Operating Hours",
      "Cleaning of Shopping Centres / Supermarkets / Retail Premises During Business Hours",
    ],
    totalAmountPaidToSubContractors: 1241,
    subContractorActivities: "Cupidatat eum tempor",
    subContractorsHoldInsurance: "yes",
    totalAmountPaidToLabourHire: 4221,
    labourHireActivities: "Natus culpa omnis i",
    labourHireHoldInsurance: "yes",
    contractualHoldHarmlessAgreementsDetails: "Deserunt blanditiis ",
    disclosureInsuranceDeclined: "yes",
    disclosureInsuranceRenewal: "yes",
    disclosureInsuranceExcess: "yes",
    disclosureInsuranceRejected: "yes",
    disclosureInsuranceBankrupt: "yes",
    disclosureInsuranceCriminal: "yes",
    disclosureInsuranceClaims: "yes",
    confirmDisclosure: true,
    disclosureInsuranceDeclinedDetails: "Quia a ullamco eveni",
    disclosureInsuranceRenewalDetails: "Assumenda voluptas m",
    disclosureInsuranceExcessDetails: "Ducimus sit laboru",
    disclosureInsuranceRejectedDetails: "Magnam consequatur ",
    disclosureInsuranceBankruptDetails: "Rem modi et quis bla",
    disclosureInsuranceCriminalDetails: "Eaque aut sit labor",
    disclosureInsuranceClaimsDetails: "In doloribus sint et",
  },
  insuranceType: "cleaners",
};
